### PR TITLE
update url in sample settings to point to new location

### PR DESCRIPTION
**Pull request by k-nut**
The fisbroker changed the location of the WFS services which led to the script not working anymore.

This change points them to the new locations

### CODE REVIEW

**Comment by micgro42** [comment]
These settings seem to work well. :+1: :shipit: 

<sup>(However I've only downloaded a few batches to verify that the download works, I have not checked the actually downloaded data.)</sup>

**Comment by johnjohndoe** [comment]
@k-nut I rebased your branch.

---

I am trying to run this on Python 3.5.2 but it fails:

> download.py: error: service not found

**Comment by k-nut** [comment]
@johnjohndoe did you copy the settings over from `settings.sample.py` to `settings.py`?

**Comment by johnjohndoe** [comment]
Yes, I did.

**Comment by k-nut** [comment]
@johnjohndoe is it possible that you maybe still have the compiled python (`settings.pyc`) file in you folder? In that case python would read that file and not the newly updated `settings.py`.

**Comment by johnjohndoe** [comment]
@k-nut Yes. The `settings.pyc` was there. But although I deleted it as well as the local `__pycache__/` folder I still run into the same error. I even cloned the repository from scratch - that did not help it.  :disappointed: 

_// btw: I rebased your branch._

**Comment by johnjohndoe** [comment]
@jochenklar Did you resolve the problems?

**Comment by jochenklar** [comment]
@johnjohndoe works for me ;)

**Comment by jochenklar** [comment]
All fun aside, I think you need to elaborate more on your particular problem. Maybe in a separate issue. It works with Python 3.6.1.

**Comment by johnjohndoe** [comment]
I am using Python 3.5.2 as stated above. Can you confirm the issue for this version?

**Comment by k-nut** [comment]
Can you post the full output for how you call the script and the complete traceback @johnjohndoe?

**Pull request merged**
